# Generated by Django 2.1.2 on 2018-11-09 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='state',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(through='volmap.Signup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signup',
            name='achieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volmap.Activity'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
