# Generated by Django 2.1.2 on 2018-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volmap', '0002_auto_20181110_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='site',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='brief',
            field=models.TextField(max_length=200),
        ),
    ]
